services:
  # Backend API Service
  - type: web
    name: menu-dashboard-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_simple:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: WHATSAPP_NUMBER
        sync: false
    autoDeploy: true

  # Frontend Static Site
  - type: web
    name: menu-dashboard-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://menu-dashboard-backend.onrender.com
    autoDeploy: true 